sudo: false
matrix:
  fast_finish: true

language: go
go:
  - "1.13.x"

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - golangci-lint run
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
  email: false
